services:
  backend:
    build: ./backend
    restart: unless-stopped
    image: workhard2021/pbi:pbi-node
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - pbi-network
  frontend:
    build: ./frontend
    restart: unless-stopped
    image: workhard2021/pbi:pbi-ang
    networks:
      - pbi-network
    ports:
      - "80:4200"
networks:
   pbi-network: