name: Push Docker Image frontend and backend
on:
  push:
    branches:
      - frontend
      - backend
    paths-ignore: ["**.md"]
  pull_request:
    branches:
      - frontend
      - backend
    paths-ignore: ["**.md"]
env:
   version: v1

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    steps:
      - name: echo
        run: |
           echo "-------------Systeme d'exploitation--------"
           echo "${{matrix.os}}"
           echo "----------------Version---------------------"
           echo ${{env.version}}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image backend
        run: docker build ./backend -t ${{secrets.DOCKER_USERNAME}}/pbi:backend

      - name: Push Docker image backend
        run: docker push ${{secrets.DOCKER_USERNAME}}/pbi:backend
  
      - name: Build Docker image frontend
        run: docker build ./frontend -t ${{secrets.DOCKER_USERNAME}}/pbi:frontend

      - name: Push Docker image frontend
        run: docker push ${{secrets.DOCKER_USERNAME}}/pbi:frontend
      #- name: Deploy to Production Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     username: ${{secrets.SSH_USER}}
      #     key: ${{secrets.SSH_PRIVATE_KEY}}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd /application-js/e-shopging && pwd
      #       # remove the existing
      #       docker-compose down
      #       #up container
      #       docker compose up -d --build
      #       #show container process
      #       docker compose ps -a
      